### ISSUE TITLE
[Errno 2] No such file or directory: 'user_audio.wav'

### ISSUE THREAD

**Issue by cedriclmao** [aisotooru/recognition-bot-discord#1]
Hi i tried your code and got this error when i  added except Exception as e: print(e)

Can you help me or contact me on Discord: Quikz#4385

**Comment by saykachi** [comment]
Hello! This code was written automatically via ChatGPT (I forgot to mention this) Try asking this neural network 90% it will help you. Now unfortunately there is no time to help you friend :(

**Comment by cedriclmao** [comment]
Okay thanks. I found out myself that this code wont and cant work technically.
